template_bucket_name: spv-wallet-test-template
file_asset_bucket_name_prefix: spv-wallet-test-marketplace-assets
file_asset_region_set:
  - 'eu-central-1'
  - 'us-east-1'
file_asset_prefix: spv-wallet/latest/
helm_chart_version: 0.2.0
