template_bucket_name: spv-wallet-test-template
file_asset_bucket_name_prefix: spv-wallet-test-marketplace-assets
file_asset_region_set:
  - 'ap-south-1'
  - 'ap-northeast-1'
  - 'ap-northeast-2'
  - 'ap-northeast-3'
  - 'ap-southeast-1'
  - 'ap-southeast-2'
  - 'ca-central-1'
  - 'eu-central-1'
  - 'eu-west-1'
  - 'eu-west-2'
  - 'eu-west-3'
  - 'eu-north-1'
  - 'sa-east-1'
  - 'us-east-1'
  - 'us-east-2'
  - 'us-west-1'
  - 'us-west-2'
file_asset_prefix: spv-wallet/latest/
helm_chart_version: 0.3.0
